<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <Description>Fast.Admin 应用入口启动层。</Description>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="logs\**" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)src\Admin.Service\Fast.Admin.Service.csproj" />
        <ProjectReference Include="$(SolutionDir)src\Center.Service\Fast.Center.Service.csproj" />
        <ProjectReference Include="$(SolutionDir)src\Scheduler.Service\Fast.Scheduler.Service.csproj" />
        <ProjectReference Include="$(SolutionDir)src\Walkman.Service\Fast.Walkman.Service.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="IGeekFan.AspNetCore.Knife4jUI" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson" />
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
        <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" />
    </ItemGroup>

</Project>
