/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Auto-generated by fast component-auto-import
// Generated by fast-vite-plugins
// Do not edit this file manually

import type { App } from "vue";

import AccountSelectPage from "./AccountSelectPage/index.vue";
export { AccountSelectPage };
export type AccountSelectPageInstance = InstanceType<typeof AccountSelectPage>;
import CitySelect from "./CitySelect/index.vue";
export { CitySelect };
export type CitySelectInstance = InstanceType<typeof CitySelect>;
import ColorPicker from "./ColorPicker/index.vue";
export { ColorPicker };
export type ColorPickerInstance = InstanceType<typeof ColorPicker>;
import Editor from "./Editor/index.vue";
export { Editor };
export type EditorInstance = InstanceType<typeof Editor>;
import EmployeeDialogSelect from "./EmployeeDialogSelect/index.vue";
export { EmployeeDialogSelect };
export type EmployeeDialogSelectInstance = InstanceType<typeof EmployeeDialogSelect>;
import EmployeeSelectPage from "./EmployeeSelectPage/index.vue";
export { EmployeeSelectPage };
export type EmployeeSelectPageInstance = InstanceType<typeof EmployeeSelectPage>;
import FastTable from "./FastTable/index.tsx";
export { FastTable };
export type FastTableInstance = InstanceType<typeof FastTable>;
import Footer from "./Footer/index.vue";
export { Footer };
export type FooterInstance = InstanceType<typeof Footer>;
import IconSelect from "./IconSelect/index.vue";
export { IconSelect };
export type IconSelectInstance = InstanceType<typeof IconSelect>;
import Loading from "./Loading/index.vue";
export { Loading };
export type LoadingInstance = InstanceType<typeof Loading>;
import MerchantSelect from "./MerchantSelect/index.vue";
export { MerchantSelect };
export type MerchantSelectInstance = InstanceType<typeof MerchantSelect>;
import ProvinceSelect from "./ProvinceSelect/index.vue";
export { ProvinceSelect };
export type ProvinceSelectInstance = InstanceType<typeof ProvinceSelect>;
import RadioGroup from "./RadioGroup/index.vue";
export { RadioGroup };
export type RadioGroupInstance = InstanceType<typeof RadioGroup>;
import RegionSelect from "./RegionSelect/index.vue";
export { RegionSelect };
export type RegionSelectInstance = InstanceType<typeof RegionSelect>;
import Tag from "./Tag/index.vue";
export { Tag };
export type TagInstance = InstanceType<typeof Tag>;
import Tendril from "./Tendril/index.vue";
export { Tendril };
export type TendrilInstance = InstanceType<typeof Tendril>;
import Text from "./Text/index.vue";
export { Text };
export type TextInstance = InstanceType<typeof Text>;
import Watermark from "./Watermark/index.vue";
export { Watermark };
export type WatermarkInstance = InstanceType<typeof Watermark>;

/** 自动注册所有组件 */
export function registerComponents(app: App): void {
	app.component(AccountSelectPage.name, AccountSelectPage);
	app.component(CitySelect.name, CitySelect);
	app.component(ColorPicker.name, ColorPicker);
	app.component(Editor.name, Editor);
	app.component(EmployeeDialogSelect.name, EmployeeDialogSelect);
	app.component(EmployeeSelectPage.name, EmployeeSelectPage);
	app.component(FastTable.name, FastTable);
	app.component(Footer.name, Footer);
	app.component(IconSelect.name, IconSelect);
	app.component(Loading.name, Loading);
	app.component(MerchantSelect.name, MerchantSelect);
	app.component(ProvinceSelect.name, ProvinceSelect);
	app.component(RadioGroup.name, RadioGroup);
	app.component(RegionSelect.name, RegionSelect);
	app.component(Tag.name, Tag);
	app.component(Tendril.name, Tendril);
	app.component(Text.name, Text);
	app.component(Watermark.name, Watermark);
}

