<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <Description>Fast.Admin 应用入口启动层。</Description>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="logs\**" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)src\Services\Admin\Fast.Admin.Service.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="IGeekFan.AspNetCore.Knife4jUI" Version="0.0.16" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson" Version="10.0.5" />
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.5" />
        <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="10.1.5" />
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <Content Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Update="appsettings.Development.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <Content Update="appsettings.json">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Content>
        <Content Update="appsettings.Development.json">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
