<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Fast.Admin 应用概念随听实体库。</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Fast.SqlSugar" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)src\Shared\Fast.Shared.csproj" />
    </ItemGroup>

</Project>