import Footer from "./footer/index.vue";
import Icon from "./icon/index.vue";
import Image from "./image/index.vue";
import ImageCaptcha from "./imageCaptcha/index.vue";
import Loading from "./loading/index.vue";
import LoadingPage from "./loadingPage/index.vue";
import NavbarCapsule from "./navbarCapsule/index.vue";
import Overlay from "./overlay/index.vue";
import Popup from "./popup/index.vue";
import SearchInput from "./searchInput/index.vue";
import TabBar from "./tabBar/index.vue";
import Tag from "./tag/index.vue";
import Watermark from "./watermark/index.vue";

export { Footer };
export type FaFooterInstance = InstanceType<typeof Footer>;
export { Icon };
export type FaIconInstance = InstanceType<typeof Icon>;
export { Image };
export type FaImageInstance = InstanceType<typeof Image>;
export { ImageCaptcha };
export type FaImageCaptchaInstance = InstanceType<typeof ImageCaptcha>;
export { Loading };
export type FaLoadingInstance = InstanceType<typeof Loading>;
export { LoadingPage };
export type FaLoadingPageInstance = InstanceType<typeof LoadingPage>;
export { NavbarCapsule };
export type FaNavbarCapsuleInstance = InstanceType<typeof NavbarCapsule>;
export { Overlay };
export type FaOverlayInstance = InstanceType<typeof Overlay>;
export { Popup };
export type FaPopupInstance = InstanceType<typeof Popup>;
export { SearchInput };
export type FaSearchInputInstance = InstanceType<typeof SearchInput>;
export { TabBar };
export type FaTabBarInstance = InstanceType<typeof TabBar>;
export { Tag };
export type FaTagInstance = InstanceType<typeof Tag>;
export { Watermark };
export type FaWatermarkInstance = InstanceType<typeof Watermark>;
